# Generated by Django 3.0 on 2019-12-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20191208_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='money',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Money',
        ),
    ]
